/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pruebas;

import clases.Bolsa;
import clases.Jugador;
import clases.Turnos;

/**
 *
 * @author palco
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        labelMaquina = new javax.swing.JLabel();
        labelBolsaPersona = new javax.swing.JLabel();
        labelPuntosMaquina = new javax.swing.JLabel();
        labelIntentosMaquina = new javax.swing.JLabel();
        labelIntentosPersona = new javax.swing.JLabel();
        labelPuntosPersona = new javax.swing.JLabel();
        labelPersona1 = new javax.swing.JLabel();
        labelBolsaPersona1 = new javax.swing.JLabel();
        labelBolsaPersona2 = new javax.swing.JLabel();
        labelBolsaPersona3 = new javax.swing.JLabel();
        tituloNivel = new javax.swing.JTextField();
        textIntentosMaquina = new javax.swing.JTextField();
        textPuntosMaquina = new javax.swing.JTextField();
        textIntentosPersona = new javax.swing.JTextField();
        textPuntosPersona = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        bolsaPersona = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        bolsaMaquina = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        numsOrdenadosMaquina = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        numsOrdenadosPersona = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        btnIniciarJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tower ");
        setBackground(new java.awt.Color(51, 153, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(51, 153, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMaquina.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        labelMaquina.setForeground(new java.awt.Color(255, 255, 255));
        labelMaquina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMaquina.setText("Maquina");
        fondo.add(labelMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, -1));

        labelBolsaPersona.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelBolsaPersona.setForeground(new java.awt.Color(255, 255, 255));
        labelBolsaPersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBolsaPersona.setText("Ordenado");
        fondo.add(labelBolsaPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 110, -1));

        labelPuntosMaquina.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        labelPuntosMaquina.setForeground(new java.awt.Color(255, 255, 255));
        labelPuntosMaquina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPuntosMaquina.setText("Puntos");
        fondo.add(labelPuntosMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, -1));

        labelIntentosMaquina.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        labelIntentosMaquina.setForeground(new java.awt.Color(255, 255, 255));
        labelIntentosMaquina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIntentosMaquina.setText("Intentos");
        fondo.add(labelIntentosMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, -1));

        labelIntentosPersona.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        labelIntentosPersona.setForeground(new java.awt.Color(255, 255, 255));
        labelIntentosPersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIntentosPersona.setText("Intentos");
        fondo.add(labelIntentosPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 100, -1));

        labelPuntosPersona.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        labelPuntosPersona.setForeground(new java.awt.Color(255, 255, 255));
        labelPuntosPersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPuntosPersona.setText("Puntos");
        fondo.add(labelPuntosPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 100, -1));

        labelPersona1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        labelPersona1.setForeground(new java.awt.Color(255, 255, 255));
        labelPersona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPersona1.setText("Persona");
        fondo.add(labelPersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 100, -1));

        labelBolsaPersona1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelBolsaPersona1.setForeground(new java.awt.Color(255, 255, 255));
        labelBolsaPersona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBolsaPersona1.setText("Bolsa");
        fondo.add(labelBolsaPersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 80, -1));

        labelBolsaPersona2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelBolsaPersona2.setForeground(new java.awt.Color(255, 255, 255));
        labelBolsaPersona2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBolsaPersona2.setText("Bolsa");
        fondo.add(labelBolsaPersona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 90, -1));

        labelBolsaPersona3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelBolsaPersona3.setForeground(new java.awt.Color(255, 255, 255));
        labelBolsaPersona3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBolsaPersona3.setText("Ordenado");
        fondo.add(labelBolsaPersona3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 110, -1));

        tituloNivel.setEditable(false);
        tituloNivel.setBackground(new java.awt.Color(255, 255, 255));
        tituloNivel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        tituloNivel.setForeground(new java.awt.Color(0, 0, 0));
        tituloNivel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tituloNivel.setText("NIVEL UNO: NUMEROS DEL 1 AL 50");
        tituloNivel.setBorder(null);
        fondo.add(tituloNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 480, 50));

        textIntentosMaquina.setEditable(false);
        textIntentosMaquina.setBackground(new java.awt.Color(255, 255, 255));
        textIntentosMaquina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textIntentosMaquina.setForeground(new java.awt.Color(0, 0, 0));
        textIntentosMaquina.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textIntentosMaquina.setText("sad");
        textIntentosMaquina.setBorder(null);
        fondo.add(textIntentosMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 40));

        textPuntosMaquina.setEditable(false);
        textPuntosMaquina.setBackground(new java.awt.Color(255, 255, 255));
        textPuntosMaquina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPuntosMaquina.setForeground(new java.awt.Color(0, 0, 0));
        textPuntosMaquina.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textPuntosMaquina.setText("sad");
        textPuntosMaquina.setBorder(null);
        fondo.add(textPuntosMaquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 40));

        textIntentosPersona.setEditable(false);
        textIntentosPersona.setBackground(new java.awt.Color(255, 255, 255));
        textIntentosPersona.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textIntentosPersona.setForeground(new java.awt.Color(0, 0, 0));
        textIntentosPersona.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textIntentosPersona.setText("sad");
        textIntentosPersona.setBorder(null);
        textIntentosPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIntentosPersonaActionPerformed(evt);
            }
        });
        fondo.add(textIntentosPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 100, 40));

        textPuntosPersona.setBackground(new java.awt.Color(255, 255, 255));
        textPuntosPersona.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textPuntosPersona.setForeground(new java.awt.Color(0, 0, 0));
        textPuntosPersona.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textPuntosPersona.setText("sd");
        textPuntosPersona.setBorder(null);
        textPuntosPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPuntosPersonaActionPerformed(evt);
            }
        });
        fondo.add(textPuntosPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 100, 40));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        fondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 20, 260));

        bolsaPersona.setEditable(false);
        bolsaPersona.setBackground(new java.awt.Color(255, 255, 255));
        bolsaPersona.setColumns(2);
        bolsaPersona.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bolsaPersona.setForeground(new java.awt.Color(0, 0, 0));
        bolsaPersona.setRows(5);
        jScrollPane1.setViewportView(bolsaPersona);

        fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 60, 200));

        bolsaMaquina.setEditable(false);
        bolsaMaquina.setBackground(new java.awt.Color(255, 255, 255));
        bolsaMaquina.setColumns(2);
        bolsaMaquina.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bolsaMaquina.setForeground(new java.awt.Color(0, 0, 0));
        bolsaMaquina.setRows(5);
        bolsaMaquina.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(bolsaMaquina);

        fondo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 60, 200));

        numsOrdenadosMaquina.setEditable(false);
        numsOrdenadosMaquina.setBackground(new java.awt.Color(255, 255, 255));
        numsOrdenadosMaquina.setColumns(2);
        numsOrdenadosMaquina.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numsOrdenadosMaquina.setForeground(new java.awt.Color(0, 0, 0));
        numsOrdenadosMaquina.setRows(5);
        numsOrdenadosMaquina.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane3.setViewportView(numsOrdenadosMaquina);

        fondo.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 60, 200));

        numsOrdenadosPersona.setEditable(false);
        numsOrdenadosPersona.setBackground(new java.awt.Color(255, 255, 255));
        numsOrdenadosPersona.setColumns(2);
        numsOrdenadosPersona.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numsOrdenadosPersona.setForeground(new java.awt.Color(0, 0, 0));
        numsOrdenadosPersona.setRows(5);
        jScrollPane4.setViewportView(numsOrdenadosPersona);

        fondo.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 60, 200));

        jButton1.setText("ORDENAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        fondo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 110, 40));

        btnIniciarJuego.setText("INICIAR");
        btnIniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarJuegoActionPerformed(evt);
            }
        });
        fondo.add(btnIniciarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 110, 40));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textIntentosPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIntentosPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIntentosPersonaActionPerformed

    private void textPuntosPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPuntosPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPuntosPersonaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnIniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarJuegoActionPerformed
        Jugador persona = new Jugador();
        Jugador maquina = new Jugador();
       
        
        textIntentosMaquina.setText(maquina.getIntentos()+"");
        textIntentosPersona.setText(persona.getIntentos()+"");
        textPuntosMaquina.setText(maquina.getPuntos()+"");
        textPuntosPersona.setText(persona.getPuntos()+"");
        
        
        
        
//        persona.bolsa.setKeysBolsa(2, 0);
//        persona.bolsa.setKeysBolsa(0, 1);
//        persona.bolsa.setKeysBolsa(0, 2);
//        persona.bolsa.setKeysBolsa(0, 3);
//        persona.bolsa.setKeysBolsa(0, 4);
//        
//        maquina.bolsa.setKeysBolsa(45, 0);
//        maquina.bolsa.setKeysBolsa(0, 1);
//        maquina.bolsa.setKeysBolsa(0, 2);
//        maquina.bolsa.setKeysBolsa(0, 3);
//        maquina.bolsa.setKeysBolsa(0, 4);
//  
        
        for (int i = 0; i < 5; i++) {
            bolsaMaquina.append(maquina.bolsa.getBolsa(i)+"\n");
            bolsaPersona.append(persona.bolsa.getBolsa(i)+"\n");
        }
        
    }//GEN-LAST:event_btnIniciarJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bolsaMaquina;
    private javax.swing.JTextArea bolsaPersona;
    private javax.swing.JButton btnIniciarJuego;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBolsaPersona;
    private javax.swing.JLabel labelBolsaPersona1;
    private javax.swing.JLabel labelBolsaPersona2;
    private javax.swing.JLabel labelBolsaPersona3;
    private javax.swing.JLabel labelIntentosMaquina;
    private javax.swing.JLabel labelIntentosPersona;
    private javax.swing.JLabel labelMaquina;
    private javax.swing.JLabel labelPersona1;
    private javax.swing.JLabel labelPuntosMaquina;
    private javax.swing.JLabel labelPuntosPersona;
    private javax.swing.JTextArea numsOrdenadosMaquina;
    private javax.swing.JTextArea numsOrdenadosPersona;
    private javax.swing.JTextField textIntentosMaquina;
    private javax.swing.JTextField textIntentosPersona;
    private javax.swing.JTextField textPuntosMaquina;
    private javax.swing.JTextField textPuntosPersona;
    private javax.swing.JTextField tituloNivel;
    // End of variables declaration//GEN-END:variables
}
